name: ubuntu-frame
adopt-info: ubuntu-frame
summary: The foundation for many embedded graphical display implementations
description: ubuntu-frame is a simple fullscreen shell (based on Wayland) used for kiosks, industrial displays, digital signage, smart mirrors, etc.
confinement: strict
base: core20
license: GPL-3.0
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

environment:
  # Prep for Mir
  MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
  LIBINPUT_QUIRKS_DIR: ${SNAP}/usr/share/libinput
  # Setup EGL from the plugs
  LD_LIBRARY_PATH:    $SNAP/graphics/lib
  LIBGL_DRIVERS_PATH: $SNAP/graphics/dri

layout:
  /usr/share:
    bind: $SNAP/usr/share
  /usr/share/libdrm:  # Needed by mesa-core20 on ARM GPUs
    bind: $SNAP/graphics/libdrm

apps:
  ubuntu-frame:
    command-chain: [bin/run-user, bin/run-frame]
    command: usr/local/bin/frame
    plugs:
      - login-session-control
      - x11

  daemon:
    command-chain: [bin/run-daemon, bin/run-frame]
    command: usr/local/bin/frame
    daemon: simple
    restart-delay: 3s
    environment:
      # XDG config
      XDG_CONFIG_HOME: $SNAP_DATA

slots:
  wayland:

plugs:
  opengl:
  graphics-core20:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core20

parts:
  recipe-version:
    plugin: nil
    source: .
    source-type: git
    override-build: |
      git rev-list --count HEAD > $SNAPCRAFT_PART_INSTALL/recipe-version
    prime:
      - -recipe-version

  ppa-setup:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -y ppa:mir-team/release
      snapcraftctl pull

  ubuntu-frame:
    after: [recipe-version, ppa-setup]
    override-pull: |
      snapcraftctl pull
      mir_version=`LANG=C apt-cache policy mir-graphics-drivers-desktop | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      recipe_version=`cat $SNAPCRAFT_STAGE/recipe-version`
      snapcraftctl set-version $recipe_version-mir$mir_version
      if echo $mir_version | grep -e '+dev' -e '~rc' -q; then snapcraftctl set-grade devel; else snapcraftctl set-grade stable; fi
    plugin: cmake
    source: src
    override-build: |
      sudo apt install --assume-yes libmiral-dev
      snapcraftctl build
    build-packages:
      - pkg-config
      - libmiral-dev
      - libwayland-dev
      - libboost1.71-dev
    stage-packages:
      - libmiral4
    prime:
      - -usr/doc
      - -usr/doc-base
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/libdrm
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
      - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libdrm.so*
      - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libglapi.so*

  platform:
    after: [ppa-setup]
    plugin: nil
    stage-packages:
      - mir-platform-graphics-gbm-kms
      - mir-platform-graphics-x
    prime:
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
      - usr/share/libinput
      - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libdrm.so*
      - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libglapi.so*
      - -usr/share/doc

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]
    prime:
      - -usr/share/doc

  scripts:
    plugin: dump
    source: scripts
