name: ubuntu-frame
adopt-info: ubuntu-frame
summary: The foundation for many embedded graphical display implementations
description: ubuntu-frame is a simple fullscreen shell (based on Wayland) used for kiosks, industrial displays, digital signage, smart mirrors, etc.
confinement: strict
base: core20
license: GPL-3.0
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

environment:
  # Prep for Mir
  MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
  LIBINPUT_QUIRKS_DIR: ${SNAP}/usr/share/libinput
  # Setup EGL from the plugs
  LD_LIBRARY_PATH:    $SNAP/graphics/lib
  LIBGL_DRIVERS_PATH: $SNAP/graphics/dri
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/graphics/glvnd/egl_vendor.d
  # Setup XKB
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb

layout:
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/libdrm:  # Needed by mesa-core20 on ARM GPUs
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    bind: $SNAP/graphics/drirc.d

apps:
  ubuntu-frame:
    command-chain: [bin/run-user, bin/run-frame]
    command: usr/local/bin/frame
    plugs:
      - opengl                # for compositing
      - login-session-control # to run as a user login (e.g. from a VT)
      - x11                   # to run on a host X11 server
      - network-bind          # to run via X-forwarding (e.g. development in a container/VM)
    slots:
      - wayland

  daemon:
    command-chain: [bin/run-daemon, bin/run-frame]
    command: usr/local/bin/frame
    daemon: simple
    restart-delay: 3s
    environment:
      # XDG config
      XDG_CONFIG_HOME: $SNAP_DATA
    plugs:
      - opengl
    slots:
      - wayland

plugs:
  graphics-core20:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core20

parts:
  recipe-version:
    plugin: nil
    source: .
    source-type: git
    override-build: |
      git rev-list --count HEAD > $SNAPCRAFT_PART_INSTALL/recipe-version
    prime:
      - -recipe-version

  ppa-setup:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -y ppa:mir-team/release
      snapcraftctl pull

  mir-git:
    plugin: cmake
    source: https://github.com/MirServer/mir.git
    source-branch: pass-socket-fd-to-miral
    source-depth: 1
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DMIR_ENABLE_TESTS=OFF
      - -DMIR_PLATFORM='gbm-kms;eglstream-kms;x11;wayland'
    build-packages:
      - build-essential
      - xsltproc
      - protobuf-compiler
      - libdrm-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libgl1-mesa-dev
      - libgbm-dev
      - libglm-dev
      - libprotobuf-dev
      - libgoogle-glog-dev
      - liblttng-ust-dev
      - libxkbcommon-dev
      - libumockdev-dev
      - umockdev
      - libudev-dev
      - libgtest-dev
      - google-mock
      - libxml++2.6-dev
      - libglib2.0-dev
      - libfreetype6-dev
      - libevdev-dev
      - libinput-dev
      - uuid-dev
      - python3
      - nettle-dev
      - libcapnp-dev
      - capnproto
      - libepoxy-dev
      - python3-pil
      - libxcb-composite0-dev
      - libxcursor-dev
      - libyaml-cpp-dev
      - systemtap-sdt-dev
      - eglexternalplatform-dev
      - libnvidia-egl-wayland-dev
        # Below are the ones that had a version bump in core20
      - libboost1.71-dev
      - libboost-date-time1.71-dev
      - libboost-program-options1.71-dev
      - libboost-system1.71-dev
      - libboost-filesystem1.71-dev
      - libboost-iostreams1.71-dev
      - libx11-xcb-dev
      - libxkbcommon-x11-dev
    stage-packages:
      - libdrm2
      - libegl1-mesa
      - libgles2
      - libwayland-server0
      - libxcursor1
      - libxfixes3
      - libxrender1
      - libfreetype6
      - libgflags2.2
      - libgoogle-glog0v5
      - liblttng-ust0
      - libunwind8
      - liburcu6
      - libwayland-egl1-mesa
      - libxcb-composite0
      - libxcb-render0
      - libevdev-dev
      - libgudev-1.0-0
      - libinput10
      - libmtdev1
      - libwacom2
      - libxkbcommon0
      - uuid-runtime
      - libglibmm-2.4-1v5
      - libsigc++-2.0-0v5
      - libxml++2.6-2v5
      - libnvidia-egl-wayland1
      #- inotify-tools
        # Below are the ones that had a version bump in core20
      - libboost-iostreams1.71.0
      - libboost-system1.71.0
      - libboost-filesystem1.71.0
      - libboost-program-options1.71.0
      - libcapnp-0.7.0
      - libprotobuf-lite17
      - libyaml-cpp0.6
      - libx11-xcb1
      - libxkbcommon-x11-0

  ubuntu-frame:
    after: [mir-git, recipe-version, ppa-setup]
    override-pull: |
      snapcraftctl pull
      mir_version=`LANG=C apt-cache policy mir-graphics-drivers-desktop | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      recipe_version=`cat $SNAPCRAFT_STAGE/recipe-version`
      snapcraftctl set-version $recipe_version-mir$mir_version
      if echo $mir_version | grep -e '+dev' -e '~rc' -q; then snapcraftctl set-grade devel; else snapcraftctl set-grade stable; fi
    plugin: cmake
    source: src
    override-build: |
      sudo apt install --assume-yes libmiral-dev
      snapcraftctl build
    build-packages:
      - pkg-config
      # - libmiral-dev
      - libwayland-dev
      - libboost1.71-dev
    stage-packages:
      # - libmiral4

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]

  scripts:
    plugin: dump
    source: scripts

  cleanup:
    after: [ubuntu-frame, mir-git, icons, scripts]
    plugin: nil
    build-snaps: [ mesa-core20 ]
    override-prime: |
      set -eux
      cd /snap/mesa-core20/current/egl/lib
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/{} \;
      rm -fr "$SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri"
      for CRUFT in bug doc doc-base drirc.d glvnd libdrm lintian man pkgconfig; do
        rm -rf "$SNAPCRAFT_PRIME/usr/share/$CRUFT"
      done
