name: Close Snaps

on:
  pull_request:
    types: [closed]

jobs:
  close:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1

    - name: Close obsolete channels
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${SNAPCRAFT_TOKEN}
      run: snapcraft close ubuntu-frame "edge/pr${{ github.event.number }}" || true
